name: 05 - 1 - Event Filters and Activity Types
on:
    pull_request:
        types: [opened, synchronize]
        branches: 
            - main
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: single job with single steps
              run: echo "Running whenever a PR is opened or synchronized AND base branch is main"
              
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: chyaneck the content
              run: cat README.md
   
