name: 05 - 1 - Event Filters and Activity
on:
    pull_request:
     types:
         - opened 
         - synchronize
     branches:
        - main
    workflow_dispatch:
jobs:
     echo:
        runs-on: ubunut-latest
        steps:
             - name: "PR raised"
               run: |
                   echo "Running whenever a PR is opened or synchronized AND base branch is main"