name: 05 - 2 - Event Filters and Activity Type
on:
    pull_request:
        types: [closed]
        branches: main    
jobs:
    echo:
        runs-on: ubunut-latest
        steps: 
            - name: PR closed
              run: echo "Running whenever a PR is closed"

              
    